import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Nav } from "./_components/navbar";
import "./globals.css";
import { Hero } from "./_components/herosection";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav/>
        <Hero />
        {children}
        </body>
    </html>
  );
}
